bootscripts: Ignore unknown executables

diff --git a/bootscripts/clfs/rc.d/startup b/bootscripts/clfs/rc.d/startup
--- a/bootscripts/clfs/rc.d/startup
+++ b/bootscripts/clfs/rc.d/startup
@@ -12,24 +12,28 @@
 /bin/echo "/sbin/mdev" > /proc/sys/kernel/hotplug
 /sbin/mdev -s
 
-echo -n "Setting system clock: "
-hwclock --hctosys --utc
-check_status
-
-echo "Starting fsck for root filesystem."
-fsck -T -C /
-if [ "$?" -gt 2 ]; then
-	echo "WARNING: Errors found while checking root filesystem."
-	echo "You can login as root now, the system will reboot after logout."
-	sulogin
-	reboot
-elif [ "$?" = "2" ]; then
-	echo "NOTICE: System needs to be rebooted now."
-	sleep 1
-	reboot
-else
-	echo -n "Checking root filesystem: "
+if [ -x /sbin/hwclock ]; then
+	echo -n "Setting system clock: "
+	hwclock --hctosys --utc
 	check_status
+fi
+
+if [ -x /sbin/fsck ]; then
+	echo "Starting fsck for root filesystem."
+	fsck -T -C /
+	if [ "$?" -gt 2 ]; then
+		echo "WARNING: Errors found while checking root filesystem."
+		echo "You can login as root now, the system will reboot after logout."
+		sulogin
+		reboot
+	elif [ "$?" = "2" ]; then
+		echo "NOTICE: System needs to be rebooted now."
+		sleep 1
+		reboot
+	else
+		echo -n "Checking root filesystem: "
+		check_status
+	fi
 fi
 
 echo -n "Remounting root rw: "
@@ -56,9 +60,11 @@ else
 	check_status
 fi
 
-echo -n "Enabling swap space: "
-swapon -a
-check_status
+if [ -x /sbin/swapon ]; then
+	echo -n "Enabling swap space: "
+	swapon -a
+	check_status
+fi
 
 echo -n "Setting hostname: "
 hostname -F /etc/HOSTNAME
